modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/AztechMC/Modern-Industrialization/issues"

[[mods]]
modId="modern_industrialization"
version="2.3.9"
displayName="Modern Industrialization"
displayURL="https://github.com/AztechMC/Modern-Industrialization"
logoFile="assets/modern_industrialization/milogo.png"
authors="Azerococo,Technici4n"
description='''A modern industrial mod for Minecraft.'''

[[mixins]]
config="modern_industrialization.mixins.json"

[[dependencies.modern_industrialization]]
modId="neoforge"
type="required"
versionRange="[21.1.113, 22-)"
ordering="NONE"
side="BOTH"

[[dependencies.modern_industrialization]]
modId="grandpower"
type="required"
versionRange="[3.0.0, 4)"
ordering="NONE"
side="BOTH"

[[dependencies.modern_industrialization]]
modId="guideme"
type="required"
versionRange="[21.1.5, 21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.modern_industrialization]]
modId="ae2"
type="optional"
versionRange="[19.0.12-alpha, 20)"
ordering="AFTER"
side="BOTH"

[[dependencies.modern_industrialization]]
modId="kubejs"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.modern_industrialization]]
modId="jei"
type="optional"
versionRange="[19.19.0,]"
ordering="NONE"
side="CLIENT"

#[[dependencies.modern_industrialization]]
#modId="minecraft"
#mandatory=true
## This version range declares a minimum of the current minecraft version up to but not including the next major version
#versionRange=""
#ordering="NONE"
#side="BOTH"
